// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Chart1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Temperture1 = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_TemperatureMin = NULL;
lv_obj_t * ui_TemperatureMax = NULL;
lv_obj_t * ui_ArcMin = NULL;
lv_obj_t * ui_ArcMax = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x150C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x190B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperture1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Temperture1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperture1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperture1, 0);
    lv_obj_set_y(ui_Temperture1, lv_pct(23));
    lv_obj_set_align(ui_Temperture1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Temperture1, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Temperture1, "120.5");
    lv_obj_set_style_text_color(ui_Temperture1, lv_color_hex(0x10F524), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperture1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperture1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart1, 401);
    lv_obj_set_height(ui_Chart1, 141);
    lv_obj_set_x(ui_Chart1, 0);
    lv_obj_set_y(ui_Chart1, -65);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_div_line_count(ui_Chart1, 10, 30);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 8, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 8, 2, true, 30);

    ui_TemperatureMin = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TemperatureMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureMin, -171);
    lv_obj_set_y(ui_TemperatureMin, 78);
    lv_obj_set_align(ui_TemperatureMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureMin, "99");
    lv_obj_set_style_text_color(ui_TemperatureMin, lv_color_hex(0x7599F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureMin, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureMax = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TemperatureMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureMax, 175);
    lv_obj_set_y(ui_TemperatureMax, 77);
    lv_obj_set_align(ui_TemperatureMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureMax, "99");
    lv_obj_set_style_text_color(ui_TemperatureMax, lv_color_hex(0xB5EC3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureMax, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcMin = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcMin, 119);
    lv_obj_set_height(ui_ArcMin, 114);
    lv_obj_set_x(ui_ArcMin, -171);
    lv_obj_set_y(ui_ArcMin, 78);
    lv_obj_set_align(ui_ArcMin, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcMin, 50);

    ui_ArcMax = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_ArcMax, 119);
    lv_obj_set_height(ui_ArcMax, 114);
    lv_obj_set_x(ui_ArcMax, 176);
    lv_obj_set_y(ui_ArcMax, 78);
    lv_obj_set_align(ui_ArcMax, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcMax, 50);

    uic_Chart1 = ui_Chart1;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Temperture1 = NULL;
    uic_Chart1 = NULL;
    ui_Chart1 = NULL;
    ui_TemperatureMin = NULL;
    ui_TemperatureMax = NULL;
    ui_ArcMin = NULL;
    ui_ArcMax = NULL;

}
